server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://${ip}:3306/no1?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: abc123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${ip}
    port: 6379
    password: null
    #redis默认操作0号数据库，但它有16个数据库 select x就能进入
    database: 0

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  main:
    allow-circular-references: true
ip: localhost

